# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0007_auto_20180302_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
    ]
